spring.application.name=api-gateway


server.port=8181

eureka.client.server-url.defaultZone=http://localhost:8761/eureka

# Gateway routes

# USER SERVICE ROUTE
spring.cloud.gateway.server.webflux.routes[0].id=user-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://USER-SERVICE
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/users/**

# PRODUCT SERVICE ROUTE
spring.cloud.gateway.server.webflux.routes[1].id=product-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://PRODUCT-SERVICE
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/products/**

# ORDER SERVICE ROUTE
spring.cloud.gateway.server.webflux.routes[2].id=order-service
spring.cloud.gateway.server.webflux.routes[2].uri=lb://ORDER-SERVICE
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/orders/**